//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTalk.API.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iTalk.API.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 帳戶 的當地語系化字串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 加入 的當地語系化字串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 所有使用者 的當地語系化字串。
        /// </summary>
        public static string AllUser {
            get {
                return ResourceManager.GetString("AllUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已經是你的朋友了 的當地語系化字串。
        /// </summary>
        public static string AlreadyYourFriend {
            get {
                return ResourceManager.GetString("AlreadyYourFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取消 的當地語系化字串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法找到該用戶 的當地語系化字串。
        /// </summary>
        public static string CannotFindUser {
            get {
                return ResourceManager.GetString("CannotFindUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定 的當地語系化字串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立帳戶 的當地語系化字串。
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 桌面版 的當地語系化字串。
        /// </summary>
        public static string DesktopVersion {
            get {
                return ResourceManager.GetString("DesktopVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 沒有iTalk帳戶？ 的當地語系化字串。
        /// </summary>
        public static string DonotHaveAccount {
            get {
                return ResourceManager.GetString("DonotHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 好友 的當地語系化字串。
        /// </summary>
        public static string Friend {
            get {
                return ResourceManager.GetString("Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首頁 的當地語系化字串。
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 iTalk 的當地語系化字串。
        /// </summary>
        public static string iTalk {
            get {
                return ResourceManager.GetString("iTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入 的當地語系化字串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登出 的當地語系化字串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 行動版 的當地語系化字串。
        /// </summary>
        public static string MobileVersion {
            get {
                return ResourceManager.GetString("MobileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 名稱 的當地語系化字串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼 的當地語系化字串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 再次輸入密碼 的當地語系化字串。
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入訊息。 的當地語系化字串。
        /// </summary>
        public static string PleaseInputMessage {
            get {
                return ResourceManager.GetString("PleaseInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 立即註冊 的當地語系化字串。
        /// </summary>
        public static string RegisterNow {
            get {
                return ResourceManager.GetString("RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 以姓名搜尋 的當地語系化字串。
        /// </summary>
        public static string SearchByName {
            get {
                return ResourceManager.GetString("SearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者 的當地語系化字串。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者名稱 的當地語系化字串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 必須至少有 3 個，最多 10 個英文、數字、@或底線 的當地語系化字串。
        /// </summary>
        public static string UserNameOrPasswordFormatError {
            get {
                return ResourceManager.GetString("UserNameOrPasswordFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會向您的朋友、同事、家人和所有使用 iTalk 的其他人顯示您的名稱。 的當地語系化字串。
        /// </summary>
        public static string UserNameTooltip {
            get {
                return ResourceManager.GetString("UserNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 這不是你自己嗎？ 的當地語系化字串。
        /// </summary>
        public static string Yourself {
            get {
                return ResourceManager.GetString("Yourself", resourceCulture);
            }
        }
    }
}
